// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0TcIXshKsbpy5msVcqJinWitIsKSKdqs',
    appId: '1:430421299622:web:b6bc29fcb7856f27fdbf67',
    messagingSenderId: '430421299622',
    projectId: 'trato-app-test',
    authDomain: 'trato-app-test.firebaseapp.com',
    storageBucket: 'trato-app-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0TcIXshKsbpy5msVcqJinWitIsKSKdqs',
    appId: '1:430421299622:android:b6bc29fcb7856f27fdbf67',
    messagingSenderId: '430421299622',
    projectId: 'trato-app-test',
    storageBucket: 'trato-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0TcIXshKsbpy5msVcqJinWitIsKSKdqs',
    appId: '1:430421299622:ios:b6bc29fcb7856f27fdbf67',
    messagingSenderId: '430421299622',
    projectId: 'trato-app-test',
    storageBucket: 'trato-app-test.appspot.com',
    iosBundleId: 'com.example.tratoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0TcIXshKsbpy5msVcqJinWitIsKSKdqs',
    appId: '1:430421299622:ios:b6bc29fcb7856f27fdbf67',
    messagingSenderId: '430421299622',
    projectId: 'trato-app-test',
    storageBucket: 'trato-app-test.appspot.com',
    iosBundleId: 'com.example.tratoApp',
  );
}
